import random
from pathlib import Path

labels = [
    "do_push",
    "do_add",
    "do_sub",
    "do_mul",
    "do_div",
    "do_print",
    "halt",
    "junk",
    "do_junk1",
    "do_junk2",
    "do_swap",
    "do_dup",
]

rng = random.SystemRandom()

perm = list(range(len(labels)))
rng.shuffle(perm)

inverse = [0] * len(labels)
for idx, val in enumerate(perm):
    inverse[val] = idx

lines = []
lines.append("// Autogenerated dispatch tables")
lines.append("static const std::array<void*, OP_COUNT> label_table = {")
lines.append("    " + ", ".join(f"&&{labels[i]}" for i in perm) + ",")
lines.append("};")
lines.append("static const std::array<uint8_t, OP_COUNT> label_index = {")
lines.append("    " + ", ".join(str(inverse[i]) for i in range(len(labels))) + ",")
lines.append("};")

Path("label_table.inc").write_text("\n".join(lines) + "\n")
